language: scala

scala:
  - 2.11.11

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

stages:
  - name: build
  - name: release
    if: tag IS present

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: src/main/resources/lib/libscalauast*
  skip_cleanup: true
  on:
    tags: true

jobs:
  include:
    - &linux_build
      name: 'Build in Linux'
      stage: build
      os: linux
      dist: xenial
      jdk:
        - openjdk8
      services:
        - docker
      before_install:
        - docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/bblfshd
        - docker exec -it bblfsh bblfshctl driver install --recommended
      script:
        - ./sbt assembly test
      after_failure: &failure_logs_anchor
        - docker logs bblfsh
        - ls hs_* 1> /dev/null 2>&1 && cat hs_*

    - &osx_build
      name: 'Build in OSX'
      stage: build
      os: osx
      osx_image: xcode9.3
      before_script:
        # travis osx support includes oraclejdk8 not openjdk8
        - export MACOSX_DEPLOYMENT_TARGET=10.7
        - export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/
      script:
        - ./sbt assembly

    - <<: *linux_build
      name: 'Release to Maven'
      stage: release
      before_script:
        - ASSETS_URL="https://github.com/bblfsh/scala-client/releases/download/$TRAVIS_TAG"
        - DEST_FOLDER="src/main/resources/lib"
        - wget $ASSETS_URL/libscalauast.dylib -o $DEST_FOLDER/libscalauast.dylib
        - wget $ASSETS_URL/libscalauast.so -o $DEST_FOLDER/libscalauast.so
      script:
        - openssl aes-256-cbc -K $encrypted_97aef7f4ae04_key -iv $encrypted_97aef7f4ae04_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
        - ./sbt publishLocal publishSigned sonatypeRelease
      deploy: skip
