language: scala

scala:
  - 2.11.11

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - &linux_build
      name: 'Build in Linux'
      stage: build
      os: linux
      dist: xenial
      jdk:
        - openjdk8
      services:
        - docker
      before_install:
        - docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/bblfshd
        - docker exec -it bblfsh bblfshctl driver install --recommended
      script:
        - ./sbt assembly test
      after_failure: &failure_logs_anchor
        - docker logs bblfsh
        - ls hs_* 1> /dev/null 2>&1 && cat hs_*

    - &osx_build
      name: 'Build in OSX'
      stage: build
      os: osx
      osx_image: xcode9.3
      before_install:
        # travis osx support includes oraclejdk8 not openjdk8
        - export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/
      script:
        - ./sbt assembly

    - <<: *linux_build
      name: 'Release to Maven'
      stage: release
      script:
        - ./sbt assembly
